### ISSUE TITLE
Internal server error after updating to 9.1.10

### ISSUE THREAD

**Issue by elleng85** [mollie/OpenCart#180]
I'm getting an internal server error when trying to proceed with an order while using a Mollie payment method (bancontact).

Installed mollie 9.1.10
Using OpenCart Version 2.1.0.2

The internal logs show repeatedly this:
```
PHP Notice:  Undefined variable: catalog in /home/-----/domains/shop.-----.be/public_html/vqmod/vqcache/vq2-admin_view_template_sale_order_info.tpl on line 741
PHP Notice:  Undefined variable: store_id in /home/-----/domains/shop.-----.be/public_html/vqmod/vqcache/vq2-admin_view_template_sale_order_info.tpl on line 741
```

The server logs show this:
```
Got error 'PHP message: PHP Fatal error:  Uncaught Error: Cannot instantiate abstract class Model in /home/-----/domains/shop.-----.be/public_html/system/comercia/load.php:130
Stack trace:
#0 /home/-----/domains/shop.-----.be/public_html/catalog/controller/payment/mollie/base.php(319): comercia\\Load->model('extension/total...')
#1 /home/-----/domains/shop.-----.be/public_html/vqmod/vqcache/vq2-system_engine_action.php(46): ControllerPaymentMollieBase->payment(Array)
#2 /home/-----/domains/shop.-----.be/public_html/system/engine/front.php(34): Action->execute(Object(Registry))
#3 /home/-----/domains/shop.-----.be/public_html/system/engine/front.php(29): Front->execute(Object(Action))
#4 /home/-----/domains/shop.-----.be/public_html/index.php(275): Front->dispatch(Object(Action), Object(Action))
#5 {main}
  thrown in /home/-----/domains/shop.-----.be/public_html/system/comercia/load.php on line 130
', referer: https://www.shop.-----.be/index.php?route=checkout/checkout
```

Thanks in advance

**Comment by QualityWorks** [comment]
I am assuming this has been fixed in a newer version, please reopen the topic if the issue still exists
