### ISSUE TITLE
Uncaught Mollie\Api\Exceptions\ApiException: cURL error 2: easy handle already used in multi handle 

### ISSUE THREAD

**Issue by ibotu** [mollie/OpenCart#209]
Fatal error: 
Uncaught Mollie\Api\Exceptions\ApiException: cURL error 2: easy handle already used in multi handle (see http://curl.haxx.se/libcurl/c/libcurl-errors.html). 

Field: _PhpScoper5bbb1f4b001f3\GuzzleHttp\Exception\RequestException: cURL error 2: easy handle already used in multi handle (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in /xx/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:124 Stack trace: #0 /xx/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(112): _PhpScoper5bbb1f4b001f3\GuzzleHttp\Handler\CurlFactory::createRejection(Object(_PhpScoper5bbb1f4b001f3\GuzzleHttp\Handler\EasyHandle), Array) #1 /xx/catalog/controller/payment/mollie-api-client/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(86): _PhpScoper5bbb1f4b001f3\GuzzleHttp\Handler\CurlFactory::finishError(Object(_PhpScoper5bbb1f4b001f3\GuzzleHttp\Handler\CurlH in /xx/catalog/controller/payment/mollie-api-client/src/MollieApiClient.php on line 355

**Comment by ibotu** [comment]
Got it solves my emptying the  mollie orders table in the database. 
Don't know exactly what broke together with that.

**Comment by ibotu** [comment]
issue should be open; 
getting same errors in site logs:
2020-04-21 12:53:40 - Error retrieving payment methods from Mollie: cURL error 2: easy handle already used in multi handle (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
2020-04-21 12:53:40 - Error retrieving payment method 'creditcard' from Mollie: cURL error 2:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
2020-04-21 12:53:40 - Error retrieving payment method 'ideal' from Mollie: cURL error 2:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
2020-04-21 12:53:40 - Error retrieving payment method 'paypal' from Mollie: cURL error 2:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
2020-04-21 12:53:40 - Error retrieving payment method 'sofort' from Mollie: cURL error 2:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).
2020-04-21 12:53:40 - Error retrieving payment method 'kbc' from Mollie: cURL error 2:  (see http://curl.haxx.se/libcurl/c/libcurl-errors.html).

**Comment by ibotu** [comment]
Apparently it was curl version installed on server


With the update to cPanel version 86 the EasyApache cURL library that is used by PHP extension cURL has been updated to version 7.79.1. I have downgraded it to the previously used version 7.69.1 which should resolve the issue that you have encountered. If this issue occurs again, please provide us with step by step instructions on how we can recreate it so we can investigate it.

**Comment by QualityWorks** [comment]
we're updating the mollie API in the new release of the module, that should solve this issue too

**Comment by philwelch2** [comment]
We're on GoDaddy and had issues (credit card skimming) when libcurl was auto-updated to 7.79.  Apparently, 7.79 isn't supposed to exist (7.70 is the current version), so it seems like there was hacking going on.  Rolling back fixed our issue and, as of 5/15, 7.79 was no longer 'available', so I suspect there shouldn't be any issues going forward.
