### ISSUE TITLE
v10.0.1 gives "Internal server error" message

### ISSUE THREAD

**Issue by DomoticX** [mollie/OpenCart#243]
**Using OC  v3.0.3.2:**
When in cart and want to select payment method we get the popup message "internal server error" and cannot continue to pay for the order. please solve the issue! (unfortunatly no log created)

Reverted back to v9.4.0 wich is working fine!

**update:**
Had to get the APACHE SSL ERROR LOGS from the hosting....:

```
[Fri Jan 22 22:08:38 2021] [error] PHP Fatal error:  Uncaught Exception: Error: Could not load model extension/payment/mollie_banktransfer! in website.nl/vqmod/vqcache/vq2-system_modification_system_engine_loader.php:89
[Fri Jan 22 22:08:38 2021] [error] Stack trace:
[Fri Jan 22 22:08:38 2021] [error] #0 website.nl/system/modification/catalog/controller/checkout/payment_method.php(166): Loader->model('extension/payme...')
[Fri Jan 22 22:08:38 2021] [error] #1 website.nl/vqmod/vqcache/vq2-system_modification_system_engine_action.php(79): ControllerCheckoutPaymentMethod->index()
[Fri Jan 22 22:08:38 2021] [error] #2 website.nl/catalog/controller/startup/router.php(25): Action->execute(Object(Registry))
[Fri Jan 22 22:08:38 2021] [error] #3 website.nl/vqmod/vqcache/vq2-system_modification_system_engine_action.php(79): ControllerStartupRouter->index()
[Fri Jan 22 22:08:38 2021] [error] #4 website.nl/system/engine/router.php(67): Actio
```

**Comment by QualityWorks** [comment]
this issue should be solved if you revisit the admin page for mollie after installing v10 and reload it / save the settings again.
This will fix the issue.

**Comment by DomoticX** [comment]
Confirmed the solution as stated above, thank you!, no errors atm!

**Comment by QualityWorks** [comment]
glad to hear it got fixed
